# Task tool documentation:
# 1) Basics: https://taskfile.dev/usage
# 2) Naming conventions: https://taskfile.dev/styleguide

version: '3'

env:
  AEM_ENV: '{{.AEM_ENV | default "local"}}'
  AEM_INSTANCE_PROCESSING_MODE: auto
  AEM_OUTPUT_VALUE: NONE
  JAVA_HOME:
    sh: sh aemw vendor list --output-value javaHome

dotenv:
  - '.env'              # VCS-ignored, user-specific
  - '.env.{{.AEM_ENV}}' # VCS-ignored, env-specific
  - '{{.AEM_ENV}}.env'  # VCS-tracked, env-specific

tasks:
  init:
    desc: initialize project
    cmds:
      - sh aemw project init

  setup:
    desc: start and provision AEM instances
    cmds:
      - task: start
      - task: provision
      - task: check

  resetup:
    desc: destroy then setup again AEM instances
    cmds:
      - task: destroy
      - task: setup

  start:
    desc: start AEM instances
    aliases: [ up ]
    cmd: sh aemw instance launch

  stop:
    desc: stop AEM instances
    aliases: [ down ]
    cmd: sh aemw instance stop

  restart:
    desc: restart AEM instances
    cmds:
      - task: stop
      - task: start

  destroy:
    desc: destroy AEM instances
    prompt: This will permanently delete all configured AEM instances and their data. Continue?
    deps: [ stop ]
    cmd: sh aemw instance destroy

  status:
    desc: check status of AEM instances
    env:
      AEM_OUTPUT_VALUE: ALL
    cmd: sh aemw instance status

  tail:
    desc: tail logs of AEM instances
    cmd: tail -f aem/home/var/instance/*/crx-quickstart/logs/{stdout,error}.log

  tail:author:
    desc: tail logs of AEM author instance
    cmd: tail -f aem/home/var/instance/author/crx-quickstart/logs/{stdout,error}.log

  tail:publish:
    desc: tail logs of AEM publish instance
    cmd: tail -f aem/home/var/instance/publish/crx-quickstart/logs/{stdout,error}.log

  provision:
    desc: provision AEM instances by installing packages and applying configurations
    aliases: [ configure ]
    cmds:
      - task: provision:repl-agent-publish
      - task: provision:crx

  provision:repl-agent-publish:
    desc: configure replication agent on AEM author instance
    cmd: 'sh aemw repl agent setup -A --location "author" --name "publish" --input-string "{ enabled: true, transportUri: \"{{.AEM_PUBLISH_HTTP_URL}}/bin/receive?sling:authRequestLogin=1\", transportUser: \"{{.AEM_PUBLISH_USER}}\", transportPassword: \"{{.AEM_PUBLISH_PASSWORD}}\", userId: \"admin\" }"'

  provision:crx:
    desc: enable CRX/DE on AEM instances
    cmd: 'sh aemw osgi config save --pid "org.apache.sling.jcr.davex.impl.servlets.SlingDavExServlet" --input-string "alias: /crx/server"'

  check:
    deps: [ author:check, publish:check ]

  author:check:
    desc: check health of AEM author instance
    cmds:
      - curl -s -u "{{.AEM_AUTHOR_USER}}:{{.AEM_AUTHOR_PASSWORD}}" "{{.AEM_AUTHOR_HTTP_URL}}/libs/granite/core/content/login.html" | grep -q "QUICKSTART_HOMEPAGE"
      - curl -s -u "{{.AEM_AUTHOR_USER}}:{{.AEM_AUTHOR_PASSWORD}}" "{{.AEM_AUTHOR_HTTP_URL}}/etc/replication/agents.author/publish.test.html" | grep -q "Replication (TEST) of /content successful"

  publish:check:
    desc: check health of AEM publish instance
    cmd: curl -s -u "{{.AEM_PUBLISH_USER}}:{{.AEM_PUBLISH_PASSWORD}}" "{{.AEM_PUBLISH_HTTP_URL}}/libs/granite/core/content/login.html" | grep -q "QUICKSTART_HOMEPAGE"

  build:std:
    desc: build AEM package
    cmd: sh mvnw clean install $AEM_BUILD_ARGS

  build:version:
    desc: check build tool versions
    cmds:
      - echo "JAVA_HOME='${JAVA_HOME}'"
      - sh mvnw -version

  build:root:
    desc: build AEM root project
    cmd: sh mvnw clean install -N $AEM_BUILD_ARGS && mkdir -p target && touch target/done.txt
    generates: [ target/done.txt ]
    sources: [ pom.xml ]

  build:core:
    desc: build AEM core bundle
    dir: core
    cmd: sh ../mvnw clean install verify $AEM_BUILD_ARGS
    generates: [ target/*.jar ]
    sources: [ ../pom.xml, pom.xml, src/**/*, lib/**/*, ../lint/**/* ]

  build:frontend:
    dir: ui.frontend
    desc: build AEM Frontend
    cmd: sh ../mvnw clean install $AEM_BUILD_ARGS
    generates:
      - ../ui.apps/src/main/content/jcr_root/apps/acm/spa/**/*
    sources:
      - pom.xml
      - package.json
      - '*.json'
      - '*.js'
      - src/**/*

  build:apps:structure:
    dir: ui.apps.structure
    desc: build AEM Apps Structure package
    cmd: sh ../mvnw clean install $AEM_BUILD_ARGS
    generates: [ target/*.ui.apps.structure-*.zip ]
    sources: [ pom.xml ]

  build:apps:
    dir: ui.apps
    desc: build AEM Apps package
    cmd: sh ../mvnw clean install $AEM_BUILD_ARGS
    generates: [ target/*.ui.apps-*.zip ]
    sources:
      - ../pom.xml
      - pom.xml
      - src/**/*
      - ../core/target/*.jar

  build:config:
    dir: ui.config
    desc: build AEM config package
    cmd: sh ../mvnw clean install $AEM_BUILD_ARGS
    sources: [ pom.xml, src/**/* ]
    generates: [ target/*.ui.config-*.zip ]

  build:content:
    dir: ui.content
    desc: build AEM base content package
    cmd: sh ../mvnw clean install $AEM_BUILD_ARGS
    sources: [ pom.xml, src/**/* ]
    generates: [ target/*.ui.content-*.zip ]

  build:all:
    dir: all
    desc: build AEM all package
    cmd: sh ../mvnw clean install $AEM_BUILD_ARGS
    sources:
      - pom.xml
      - src/**/*
      - ../ui.apps/target/*.ui.apps-*.zip
      - ../ui.content/target/*.ui.content-*.zip
      - ../ui.content.migration/target/*.ui.content.migration-*.zip
      - ../ui.content.permissions/target/*.ui.content.permissions-*.zip
    generates: [ target/*.all-*.zip ]

  build:inc:
    desc: build AEM application incrementally (only changed modules are rebuilt)
    cmds:
      - task: build:root
      - task: build:core
      - task: build:frontend
      - task: build:apps:structure
      - task: build:apps
      - task: build:config
      - task: build:content
      - task: build:all

  build:clean:
    desc: clean built AEM application
    cmd: sh mvnw clean

  deploy:all:
    desc: deploy all AEM package to AEM instances
    cmd: sh aemw package deploy --file "all/target/acm.all-*.zip"

  deploy:min:
    desc: deploy minimal AEM package to AEM instances
    cmd: sh aemw package deploy --file "min/target/acm.min-*.zip"

  develop:all:
    desc: build & deploy all AEM package to instances
    deps: [ build:inc ]
    cmds:
      - task: deploy:all

#  develop:min:
#    desc: build & deploy minimal AEM package to instances
#    deps: [ build ]
#    cmds:
#      #- sh aemw package deploy --url 'https://github.com/orbinson/aem-groovy-console/releases/download/19.0.5/aem-groovy-console-all-19.0.5.zip'
#      - task: deploy:min
#      - sh aemw package deploy --file 'ui.content/target/acm.ui.content-*.zip'

  develop:core:
    desc: build & deploy core OSGi bundle to instances
    cmds:
      - (cd core && sh ../mvnw clean package)
      - sh aemw osgi bundle install --file 'core/target/acm.core-*.jar'

  develop:content:
    desc: build & deploy content AEM package to instances
    cmds:
      - (cd ui.content && sh ../mvnw clean package)
      - sh aemw package deploy --file 'ui.content/target/acm.ui.content-*.zip'

  develop:content:example:
    desc: build & deploy example content AEM package to instances
    cmds:
      - (cd ui.content.example && sh ../mvnw clean package)
      - sh aemw package deploy --file 'ui.content.example/target/acm.ui.content.example-*.zip'

  develop:frontend:
    desc: build & deploy frontend to instances
    cmds:
      - (cd ui.frontend && npm install && npm run build)
      - sh aemw content push --dir 'ui.apps/src/main/content/jcr_root/apps/acm/spa'

  develop:frontend:dev:
    desc: build & deploy frontend to instances in development mode
    dir: ui.frontend
    cmds:
      - sh npmw install
      - sh npmw run dev

  develop:frontend:fix:
    desc: format frontend code
    dir: ui.frontend
    cmds:
      - sh npmw run format
      - sh npmw run lint

  release:
    desc: Release a new version
    vars:
      VERSION: ""
    cmds:
      - |
        set -e

        VERSION="{{.CLI_ARGS | default ""}}"
        VERSION_TAG="v$VERSION"

        VERSION_CURRENT_TAG=$(git describe --tags --abbrev=0 || echo "v0.0.0")
        VERSION_CURRENT_TAG="${VERSION_CURRENT_TAG#v}" # remove leading 'v', preserve leading zeros

        if [ -z "$VERSION" ]; then
            echo "Release version is not specified!"
            echo "Last released: ${VERSION_CURRENT_TAG}"
            exit 1
        fi

        GIT_STAT=$(git diff --stat || true)

        if [ "$GIT_STAT" != '' ]; then
            echo "Unable to release. Uncommitted changes detected!"
            exit 1
        fi

        echo "Releasing $VERSION_TAG"

        echo "Bumping version in files"

        echo "<TODO>"
        #README_FILE="README.MD"
        #PROJECT_WRAPPER_SCRIPT="pkg/project/common/aemw"
        #
        ## <https://stackoverflow.com/a/57766728>
        #if [ "$(uname)" = "Darwin" ]; then
        #  sed -i '' 's/AEM_CLI_VERSION:-"[^\"]*"/AEM_CLI_VERSION:-"'"$VERSION"'"/g' "$PROJECT_WRAPPER_SCRIPT"
        #  # shellcheck disable=SC2016
        #  sed -i '' 's/aem\@v[^\`]*\`/aem@v'"$VERSION"\`'/g' "$README_FILE"
        #else
        #    sed -i 's/AEM_CLI_VERSION:-"[^\"]*"/AEM_CLI_VERSION:-"'"$VERSION"'"/g' "$PROJECT_WRAPPER_SCRIPT"
        #    # shellcheck disable=SC2016
        #    sed -i 's/aem\@v[^\`]*\`/aem@v'"$VERSION"\`'/g' "$README_FILE"
        #fi

        echo "Pushing version bump"
        git commit -a -m "Release $VERSION_TAG" || echo "No changes to commit"
        git push || echo "Nothing to push"

        echo "Pushing release tag '$VERSION_TAG'"
        git tag "$VERSION_TAG"
        git push origin "$VERSION_TAG" || echo "Tag already exists or cannot push"