import org.apache.poi.ss.usermodel.*
import org.apache.poi.xssf.usermodel.XSSFWorkbook
import java.time.LocalDate
import java.time.ZoneId

/*
---
author: <john.doe@acme.com>
---
Reads an XLSX file (e.g. generated by ACME-203) and outputs summary statistics.
Demonstrates how to use file input for uploading and parsing spreadsheet files.

```mermaid
graph TD
    A[Upload XLS File] --> B[Open Workbook]
    B --> C[Read Sheet]
    C --> D[Parse Rows]
    D --> E[Calculate Statistics]
    E --> F[Output Summary]
```
*/

void describeRun() {
    inputs.file("xlsFile") {
        label = "XLS/XLSX File"
        description = "Upload a spreadsheet file to analyze (e.g. report.xlsx from ACME-203)"
        mimeTypes = [
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            "application/vnd.ms-excel"
        ]
    }
}

boolean canRun() {
    return conditions.always()
}

void doRun() {
    out.info "Reading XLS file..."

    def xlsFile = repo.get(inputs.value("xlsFile"))

    try {
        Workbook workbook = new XSSFWorkbook(xlsFile.readFileAsStream())
        Sheet sheet = workbook.getSheetAt(0)

        def rowCount = 0
        def names = [] as Set
        def surnames = [] as Set
        def oldestDate = null
        def youngestDate = null

        for (Row row : sheet) {
            if (row.getRowNum() == 0) continue // skip header

            context.checkAborted()
            rowCount++

            def nameCell = row.getCell(0)
            def surnameCell = row.getCell(1)
            def dateCell = row.getCell(2)

            if (nameCell) names.add(nameCell.getStringCellValue())
            if (surnameCell) surnames.add(surnameCell.getStringCellValue())

            if (dateCell && dateCell.getCellType() == CellType.NUMERIC && DateUtil.isCellDateFormatted(dateCell)) {
                def date = dateCell.getDateCellValue().toInstant().atZone(ZoneId.systemDefault()).toLocalDate()
                if (oldestDate == null || date.isBefore(oldestDate)) oldestDate = date
                if (youngestDate == null || date.isAfter(youngestDate)) youngestDate = date
            }

            if (rowCount % 1000 == 0) out.info("Processed ${rowCount} rows...")
        }

        workbook.close()

        outputs.text("summary") {
            label = "Summary"
            value = """
                |**Rows processed:** ${rowCount}
                |**Unique names:** ${names.size()}
                |**Unique surnames:** ${surnames.size()}
                |**Oldest birth date:** ${oldestDate ?: 'N/A'}
                |**Youngest birth date:** ${youngestDate ?: 'N/A'}
            """.stripMargin().trim()
        }

        out.success "XLS file analysis completed"
    } finally {
        xlsFile.delete()
    }
}
