group: ACL
name: acl_demo_configure_group
content: |
  acl.getGroup { id = "${1}" }?.with {
    setProperty { relPath = "myprop"; value = "myvalue" }
    removeProperty { relPath = "myprop" }
    removeAllMembers()
    removeFromAllGroups()
    clear { path = "/content" }
    purge()
    addMember { memberId = "mymember" }
    removeMember { memberId = "mymember" }
    addToGroup { groupId = "mygroup }
    removeFromGroup { groupId = "mygroup" }
    deny { path = "/content"; permissions = ["jcr:read"]; glob = "/*"; restrictions = [:] }
    allow { path = "/content/acme"; permissions = ["jcr:read"]; glob = "/*"; restrictions = [:] }
  }
documentation: |
  Demonstrates how to configure OOTB AEM groups like 'administrators' or 'contributors'.
