group: ACL
name: acl_demo_configure-user
content: |
  acl.getUser { id = "${1:id}" }?.with {
    /*
    setPassword { password = "mysecret" }
    setProperty { relPath = "myprop"; value = "myvalue" }
    removeProperty { relPath = "myprop" }
    removeFromAllGroups()
    clear { path = "/content" }
    purge()
    addToGroup { groupId = "mygroup" }
    removeFromGroup { groupId = "mygroup" }
    allow { path = "/content/acme"; permissions = ["jcr:read"]; glob = "/*"; restrictions = [:] }
    deny { path = "/content"; permissions = ["jcr:read"]; glob = "/*"; restrictions = [:] }
    */
  }
documentation: |
  Demonstrates how to configure OOTB AEM users like: 'admin' or 'anonymous'.
