name: Check

on:
  push:
    branches: [ main ]
    paths-ignore: ['**.md', 'docs/**']
  pull_request:
    branches: [ main ]
    paths-ignore: ['**.md', 'docs/**']

jobs:
  build:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        if: always()
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build Code
        run: mvn -B clean package verify
