name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Deploy to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Extract Version
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: temurin

      - name: Build all modules
        run: sh ./mvnw -B install -Drevision=${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish AEM Distribution 'All'
        working-directory: core
        run: sh ../mvnw -B deploy -Drevision=${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish AEM Distribution 'Min'
        working-directory: min
        run: sh ../mvnw -B deploy -Drevision=${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish AEM Package 'UI Content Example'
        working-directory: ui.content.example
        run: sh ../mvnw -B deploy -Drevision=${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish OSGi Bundle 'Core'
        working-directory: core
        run: sh ../mvnw -B deploy -Drevision=${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}