name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Deploy to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: write
    steps:
      - name: Extract Version
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: temurin

      - name: Build all modules
        run: sh ./mvnw -B install -Drevision=${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish AEM Distribution 'All'
        run: |
          mvn deploy:deploy-file \
            -Durl=https://maven.pkg.github.com/wttech/acm \
            -DrepositoryId=github \
            -Dfile=all/target/acm.all-${{ env.VERSION }}.zip \
            -DgroupId=com.wttech.aem.acm \
            -DartifactId=acm.all \
            -Dversion=${{ env.VERSION }} \
            -Dpackaging=zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish AEM Distribution 'Min'
        run: |
          mvn deploy:deploy-file \
            -Durl=https://maven.pkg.github.com/wttech/acm \
            -DrepositoryId=github \
            -Dfile=min/target/acm.min-${{ env.VERSION }}.zip \
            -DgroupId=com.wttech.aem.acm \
            -DartifactId=acm.min \
            -Dversion=${{ env.VERSION }} \
            -Dpackaging=zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish AEM Package 'UI Content Example'
        run: |
          mvn deploy:deploy-file \
            -Durl=https://maven.pkg.github.com/wttech/acm \
            -DrepositoryId=github \
            -Dfile=ui.content.example/target/acm.ui.content.example-${{ env.VERSION }}.zip \
            -DgroupId=com.wttech.aem.acm \
            -DartifactId=acm.ui.content.example \
            -Dversion=${{ env.VERSION }} \
            -Dpackaging=zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish OSGi Bundle 'Core'
        run: |
          mvn deploy:deploy-file \
            -Durl=https://maven.pkg.github.com/wttech/acm \
            -DrepositoryId=github \
            -Dfile=core/target/acm.core-${{ env.VERSION }}.jar \
            -DgroupId=com.wttech.aem.acm \
            -DartifactId=acm.core \
            -Dversion=${{ env.VERSION }} \
            -Dpackaging=jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false

      - name: Upload AEM Distribution 'All' to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: all/target/acm.all-${{ env.VERSION }}.zip
          asset_name: acm.all-${{ env.VERSION }}.zip
          asset_content_type: application/zip

      - name: Upload AEM Distribution 'Min' to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: min/target/acm.min-${{ env.VERSION }}.zip
          asset_name: acm.min-${{ env.VERSION }}.zip
          asset_content_type: application/zip

      - name: Upload AEM Package 'UI Content Example' to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ui.content.example/target/acm.ui.content.example-${{ env.VERSION }}.zip
          asset_name: acm.ui.content.example-${{ env.VERSION }}.zip
          asset_content_type: application/zip

      - name: Upload OSGi Bundle 'Core' to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: core/target/acm.core-${{ env.VERSION }}.jar
          asset_name: acm.core-${{ env.VERSION }}.jar
          asset_content_type: application/java-archive