name: Test

on:
  workflow_dispatch:
    inputs:
      acm_version:
        description: 'ACM Version'
        required: false
        type: string

jobs:
  e2e:
    name: 'E2E Tests'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      FORCE_COLOR: 1
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Setup NodeJS Runtime
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: './test/e2e/package-lock.json'

      - name: Setup NodeJS Dependencies
        working-directory: ./test/e2e
        run: npm ci

      - name: Setup AEM Compose
        run: |
          echo "AEM_PUBLISH_ACTIVE=false" >> .env

      - name: Setup AEM Instance
        run: |
          set -e
          mkdir -p aem/home/lib
          aws s3 cp s3://${{ secrets.AWS_S3_BUCKET_NAME }}/aem/on-prem/cq-quickstart-6.5.0.jar aem/home/lib/cq-quickstart-6.5.0.jar
          aws s3 cp s3://${{ secrets.AWS_S3_BUCKET_NAME }}/aem/on-prem/license.properties aem/home/lib/license.properties
          sh aemw instance launch

      - name: Get ACM Version
        id: acm_version
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if [ -z "${{ inputs.acm_version }}" ]; then
            VERSION=$(gh release view --repo wttech/acm --json tagName --jq '.tagName')
          else
            VERSION="${{ inputs.acm_version }}"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Deploy ACM Package
        run: |
          VERSION="${{ steps.acm_version.outputs.version }}"
          sh aemw pkg deploy --url "https://github.com/wttech/acm/releases/download/$VERSION/acm.all-$VERSION.zip"

      - name: Run Playwright Tests
        working-directory: ./test/e2e
        run: npx playwright test

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: ./test/e2e/playwright-report/
          retention-days: 30
