name: Test E2E

on: [workflow_dispatch]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Setup AEM Compose
        run: |
          curl https://raw.githubusercontent.com/wttech/aemc/main/project-install.sh | sh
          sh aemw project scaffold --project-kind instance
          echo "AEM_PUBLISH_ACTIVE=false" >> .env

      - name: Download AEM files
        run: |
          mkdir -p aem/home/lib
          aws s3 cp s3://${{ secrets.AWS_S3_BUCKET_NAME }}/aem/on-prem/cq-quickstart-6.5.0.jar aem/home/lib/cq-quickstart-6.5.0.jar
          aws s3 cp s3://${{ secrets.AWS_S3_BUCKET_NAME }}/aem/on-prem/license.properties aem/home/lib/license.properties

      - name: Start AEM instance
        run: |
          sh aemw instance launch