name: Test

on: [workflow_dispatch]

jobs:
  e2e:
    name: 'E2E Tests'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      FORCE_COLOR: 1
    defaults:
      run:
        working-directory: ./test/e2e
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Setup AEM Compose
        run: |
          curl https://raw.githubusercontent.com/wttech/aemc/main/project-install.sh | sh
          sh aemw project scaffold --project-kind instance
          echo "AEM_PUBLISH_ACTIVE=false" >> .env

      - name: Download AEM files
        run: |
          set -e
          mkdir -p aem/home/lib
          aws s3 cp s3://${{ secrets.AWS_S3_BUCKET_NAME }}/aem/on-prem/cq-quickstart-6.5.0.jar aem/home/lib/cq-quickstart-6.5.0.jar
          aws s3 cp s3://${{ secrets.AWS_S3_BUCKET_NAME }}/aem/on-prem/license.properties aem/home/lib/license.properties

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Start AEM instance
        run: |
          sh aemw instance launch

      - name: Run Playwright Tests
        run: npx playwright test

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
